schema_version: 1

context:
  version: "17.1.0"

package:
  name: keeper-secrets-manager-core
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/k/keeper-secrets-manager-core/keeper_secrets_manager_core-${{ version }}.tar.gz
  sha256: e908e05174a7ec8fe2da5ca1641d32fdc4b10c2e5b102957da52d7084f0ef698

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python =${{ python_min }}
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - requests
    - cryptography >=39.0.1
    - importlib-metadata

tests:
  - python:
      imports:
        - keeper_secrets_manager_core
  - requirements:
      run:
        - pip
        - python =${{ python_min }}
    script:
      - pip check

about:
  summary: Keeper Secrets Manager for Python 3
  license: MIT
  license_file: LICENSE.txt
  homepage: https://github.com/Keeper-Security/secrets-manager

extra:
  recipe-maintainers:
    - danielnachun
